# -*- coding: utf-8 -*-
"""CashCast.ipynb

Automatically generated by Colab.

Original file is located at
    [REDACT]

##CashCast

An web app that analyzes upcoming bills relative to account balances.
"""

#imports
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from ics import Calendar, Event

#configuring APIs, customer IDs

API_KEY = "ENTER_YOUR_API_KEY"
BASE_URL = "http://api.nessieisreal.com"

CUSTOMER_ID = "ENTER_YOUR_CUSTOMER_ID"
CHECKING_ID = "ENTER_CHECKING_ID"
SAVINGS_ID = "ENTER_SAVINGS_ID"

#API wrappers

class NessieCustomer:
  def __init__(self, api_key, base_url=BASE_URL):
      self.api_key = api_key
      self.base_url = base_url

  def get(self, endpoint):
      url = f"{self.base_url}{endpoint}?key={self.api_key}"
      return requests.get(url).json()

  def get_account_balance(self, account_id):
      r = self.get(f"/accounts/{account_id}")
      return r.get("balance", 0)

  def get_bills(self, account_id):
      r = self.get(f"/accounts/{account_id}/bills")
      bills = []
      for bill in r:
          try:
              due_date = datetime.strptime(bill["payment_date"], "%Y-%m-%dT%H:%M:%S.%fZ").date()
          except ValueError:
              due_date = datetime.strptime(bill["payment_date"], "%Y-%m-%d").date()

          bills.append({
              "due_date": due_date,
              "amount": float(bill["payment_amount"]),
              "payee": bill.get("payee", "Unknown")
              })
      return bills

  def get_deposits(self, account_id):
      r = self.get(f"/accounts/{account_id}/deposits")
      deposits = []
      for dep in r:
          #Check if 'transaction_date' exists
          transaction_date = dep.get("transaction_date")

          #If no transaction date, use today's date
          if transaction_date:
              # Try parsing with different formats
              try:
                  date = datetime.strptime(transaction_date, "%Y-%m-%dT%H:%M:%S.%fZ").date()
              except ValueError:
                  try:
                      date = datetime.strptime(transaction_date, "%Y-%m-%d").date()
                  except ValueError:
                      date = datetime.today().date() # Fallback to today if parsing fails
          else:
              date = datetime.today().date()
          deposits.append({
            "date": date,
            "amount": float(dep["amount"])
            })
      return deposits


  def get_average_daily_spend(self, account_id, lookback_days=60):
      r = self.get(f"/accounts/{account_id}/purchases")
      if not r:
          return 0.0
      purchases = pd.DataFrame(r)
      purchases["purchase_date"] = pd.to_datetime(purchases["purchase_date"])
      recent = purchases[purchases["purchase_date"] > datetime.now() - timedelta(days=lookback_days)]
      avg_spend = recent["amount"].astype(float).sum() / lookback_days
      return avg_spend

#Forecasting

class CashFlowForecaster:
  def __init__(self, customer, checking_id, savings_id=None, horizon_days=60):
      self.customer = customer
      self.checking_id = checking_id
      self.savings_id = savings_id
      self.horizon_days = horizon_days
      self.today = datetime.now().date()

      #Fetch data
      self.checking_balance = self.customer.get_account_balance(checking_id)
      self.savings_balance = self.customer.get_account_balance(savings_id)
      self.bills = self.customer.get_bills(checking_id)
      self.deposits = self.customer.get_deposits(checking_id)
      self.daily_spend = self.customer.get_average_daily_spend(checking_id)

  #Forward cash flow forecasting for checking account
  def forecast(self):
      balance = self.checking_balance
      forecast = []

      for i in range(self.horizon_days):
          current_day = self.today + timedelta(days=i)

          #add deposits
          for deposit in self.deposits:
              if deposit["date"] == current_day:
                  balance += deposit["amount"]

          #subtract bills
          for bill in self.bills:
              if bill["due_date"] == current_day:
                  balance -= bill["amount"]

          #subtract spending
          balance -= self.daily_spend

          forecast.append({"date": current_day, "balance": round(balance, 2)})

      return pd.DataFrame(forecast)

  #suggest transfers or adjustments ot avoid overdraft
  def recommend_actions(self, df_forecast):
      recommendations = []
      savings = self.savings_balance
      #print("enter recommend_actions function")

      for _, row in df_forecast.iterrows():
          if row["balance"] < 0:
              needed = abs(row["balance"])
              if savings >= needed:
                  recommendations.append({
                      "date": row["date"],
                      "action": f"Transfer ${needed:.2f} from savings to checking"
                  })
                  savings -= needed
              else:
                  recommendations.append({
                      "date": row["date"],
                      "action": f"Cut discretionary spending by ${needed:.2f}"
                  })
      #print("leaving recommend_actions function")
      return recommendations

  #Monte Carlo stress test
  def stress_test(self, runs=100):
      overdraft_probability = []
      for _ in range(runs):
          df = self.forecast()
          overdraft_probability.append((df["balance"] < 0).any())
          risk = np.mean(overdraft_probability)
          return risk

    #Export forecast & recommendation of calendar events
  def export_calendar(self, df_forecast, recommendations, filename="cashflow_forecast.ics"):
      calendar = Calendar()

      for _, row in df_forecast.iterrows():
          event = Event()
          event.name = f"Balance: ${row['balance']:.2f}"
          event.begin = datetime.combine(row["date"], datetime.min.time())
          calendar.events.add(event)

      for recommendation in recommendations:
          event = Event()
          event.name = f"Recommendation: {recommendation['action']}"
          event.begin = datetime.combine(recommendation["date"], datetime.min.time())
          calendar.events.add(event)

      with open(filename, "w") as f:
          f.writelines(calendar.serialize_iter())

#Main
if __name__ == "__main__":
    customer = NessieCustomer(API_KEY)
    forecaster = CashFlowForecaster(customer, CHECKING_ID, savings_id=SAVINGS_ID, horizon_days=60)

    #Forecasting
    df_forecast = forecaster.forecast()
    #print(df_forecast.head())

    #Recommendations
    #print("Hitting rec sections")
    recs = forecaster.recommend_actions(df_forecast)

    #print("Recommendations:")
    print(recs)
    for r in recs:
        print(F"{r['date']}: {r['action']}")

    risk = forecaster.stress_test(runs=200)
    print(f"Overdraft Probability (next {forecaster.horizon_days} days): {risk:.1%}")

    forecaster.export_calendar(df_forecast, recs)
    #print("Calendar saved!")