# -*- coding: utf-8 -*-
"""CashCast_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    [REDACT]
"""

##Dashboard for CashCast

import streamlit as st
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from cashcast import NessieCustomer, CashFlowForecaster

#Nessie API

API_KEY = "ENTER_YOUR_API_KEY"
CUSTOMER_ID = "ENTER_YOUR_CUSTOMER_ID"
CHECKING_ID = "ENTER_CHECKING_ID"
SAVINGS_ID = "ENTER_SAVINGS_ID"

def main():
    page_bg = """
    <style>
    [data-testid="stAppViewContainer"]{
      background-color: #f0f8ff;
    }
    [data-testid="stHeader"]{
      background-color: rgba(0,0,0,0);
    }
    [data-testid="stToolbar"]{
      background-color: #f0f8ff;
    }
    </style>
    """
    st.markdown(page_bg, unsafe_allow_html=True)
    st.set_page_config(page_title="Cashcast Dashboard", layout="wide")
    st.title("Cashcast: Forecast Your Finances, Stress Less")

    #sidebar for parameters
    st.sidebar.header("Settings")
    horizon_days = st.sidebar.slider("Forecast Horizon (days)", 30, 180, 60)
    daily_spend_estimate = st.sidebar.number_input("Estimated Daily Spend", min_value=0.0, step=1.0)

    #Customer & Forecaster from CashCast.py
    customer = NessieCustomer(API_KEY)
    forecaster = CashFlowForecaster(customer, CHECKING_ID, savings_id=SAVINGS_ID, horizon_days=horizon_days)

    if daily_spend_estimate > 0:
        forecaster.daily_spend = daily_spend_estimate

    #Run forecast
    df_forecast = forecaster.forecast()

    #Show account balances
    st.subheader("Account Balances")
    col1, col2 = st.columns(2)
    with col1:
        st.metric("Checking Balance", f"${forecaster.checking_balance:,.2f}")
    with col2:
        st.metric("Savings Balance", f"${forecaster.savings_balance:,.2f}")
    st.divider()

    #Plot forecast
    st.subheader("Projected Balance Over Time")
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(df_forecast["date"], df_forecast["balance"], label="Projected Balance", color="royalblue")

    #Overdraft points
    overdrafts = df_forecast[df_forecast["balance"] < 0]
    if not overdrafts.empty:
        ax.scatter(overdrafts["date"], overdrafts["balance"], color="red", label="Overdrafts", )

    ax.axhline(0, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("Date")
    ax.set_ylabel("Balance")
    ax.set_title("Cash Flow Forecast")
    plt.xticks(rotation=45, ha="right")
    ax.legend()
    st.pyplot(fig)
    st.divider()

    #Display recommendations
    st.subheader("Recommendations")
    recs = forecaster.recommend_actions(df_forecast)
    if recs:
        for r in recs:
            st.write(f"{r['date']} -> {r['action']}")
    else:
        st.success("No recommendations available. You have no predicted overdrafts.")
    st.divider()

    #Spending Variability
    st.subheader("Stress Test")
    risk = forecaster.stress_test(runs=200)
    st.metric("Overdraft Probability", f"{risk:.1%}")
    st.divider()

    # Overdraft meter
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=risk*100,
        number={'suffix': "%"},
        gauge={
            'axis': {'range': [0,100]},
            'bar': {'color': "red"},
            'bgcolor': "#D9F1FC",
            'steps': [
                {'range': [0,30], 'color': "#20BF55"},
                {'range': [30,60], 'color': "#FFBD00"},
                {'range': [60,100], 'color': "#CC2936"}
            ],
            'threshold': {
                'line': {'color': "#C9F299", 'width': 5},
                'thickness': 1,
                'value': risk * 100
            }
        },
        title={'text': "Overdraft Risk"}
    ))

    st.plotly_chart(fig, use_container_width=True)

    #Calendar Export
    st.subheader("Export Calendar")
    if st.button("Generate Calendar File"):
        forecaster.export_calendar(df_forecast, recs, filename="cashflow_forecast.ics")
        with open("cashflow_forecast.ics", "rb") as f:
            st.download_button("Download Calendar", f, file_name="cashflow_forecast.ics")
        st.success("Calendar file generated!")
    st.divider()
    with st.expander("View Raw Forecast Data"):
        st.dataframe(
            df_forecast[["date", "balance"]],
            use_container_width=True,
        )


if __name__ == "__main__":
    main()